version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_db_pg_container
    restart: always
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/1_db_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

networks:
  my_network:
